// Generated by CoffeeScript 1.4.0

define(['core/util', 'core/atom', 'core/game'], function(_util, _atom, DrawThisGame) {
  var isPreloadComplete, loaded, startGame;
  startGame = function() {
    window.game = new DrawThisGame();
    return window.game.run();
  };
  loaded = {
    gfx: false,
    sfx: false
  };
  isPreloadComplete = function() {
    if (loaded.gfx && loaded.sfx) {
      startGame();
      return true;
    } else {
      return false;
    }
  };
  atom.preloadImages({
    pen: 'pen.png'
  }, function() {
    loaded.gfx = true;
    return isPreloadComplete();
  });
  atom.preloadSounds({
    tick: 'tick.mp3'
  }, function() {
    loaded.sfx = true;
    return isPreloadComplete();
  });
});
