// Generated by CoffeeScript 1.4.0

module.exports = {
  objKeyCount: function(o) {
    var i, k, v;
    i = 0;
    for (k in o) {
      v = o[k];
      i++;
    }
    return i;
  },
  extend: function(target, extender) {
    var k, v;
    if (target == null) {
      target = {};
    }
    for (k in extender) {
      v = extender[k];
      target[k] = v;
    }
    return target;
  }
};
