// Generated by CoffeeScript 1.4.0
var $, Connection;

$ = require('./$.js');

Connection = (function() {

  function Connection(params) {
    var k, v;
    for (k in params) {
      v = params[k];
      this[k] = v;
    }
    this.registerEvents();
    this.SOCKET.emit('welcome');
    this;

  }

  Connection.prototype.NETWORK = null;

  Connection.prototype.SOCKET = null;

  Connection.prototype.registerEvents = function() {
    var _this = this;
    this.SOCKET.on('joinroom', function(d) {
      return _this.event.joinroom.call(_this, d);
    });
    return this;
  };

  Connection.prototype.event = {
    joinroom: function(data) {
      var _this = this;
      this.SOCKET._ = $.extend({}, data);
      this.NETWORK.rc.get("room " + data.room + " canvaspage", function(e, d) {
        return _this.SOCKET.emit('canvaspage', d);
      });
      this.NETWORK.rc.get("room " + data.room + " chatlog", function(e, d) {
        return _this.SOCKET.emit('chatlog', d);
      });
      this.NETWORK.rc.get("room " + data.room + " playerlist", function(e, d) {
        var newPlayerList;
        newPlayerList = d != null ? "" + d + " " + data.name : "" + data.name;
        _this.SOCKET.emit('playerlist', newPlayerList);
        return _this.NETWORK.rc.set("room " + data.room + " playerlist", newPlayerList);
      });
    },
    leaveroom: function(data) {
      var _this = this;
      this.NETWORK.rc.get("room " + this.SOCKET._.room + " playerlist", function(e, d) {
        var newPlayerList;
        if (!!(d != null)) {
          newPlayerList = d.replace(" " + _this.SOCKET._.name, '').replace("" + _this.SOCKET._.name, '');
        }
        return _this.NETWORK.rc.set("room " + _this.SOCKET._.room + " playerlist", newPlayerList);
      });
    },
    canvasline: function(data) {},
    canvaspage: function(data) {},
    chatlog: function(data) {},
    chatmsg: function(data) {}
  };

  return Connection;

})();

module.exports = Connection;
