// Generated by CoffeeScript 1.4.0
var Canvas;

Canvas = (function() {

  Canvas.prototype.lines = [];

  Canvas.prototype.lastLineCount = 0;

  function Canvas(params) {
    var k, v;
    for (k in params) {
      v = params[k];
      this[k] = v;
    }
    this;

  }

  Canvas.prototype.addLine = function(data) {};

  return Canvas;

})();

module.exports = new Canvas();
