// Generated by CoffeeScript 1.4.0

define(function() {
  var Chat;
  return Chat = (function() {

    function Chat(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      if (!(this.game != null)) {
        throw 'game was not set!';
      }
    }

    return Chat;

  })();
});
