// Generated by CoffeeScript 1.4.0

define(function() {
  var DrawingArea;
  return DrawingArea = (function() {

    DrawingArea.prototype.x = 16;

    DrawingArea.prototype.y = 16;

    DrawingArea.prototype.w = 600;

    DrawingArea.prototype.h = 400;

    function DrawingArea(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      this.drawing = [];
    }

    DrawingArea.prototype.draw = function() {
      var ac;
      ac = atom.context;
      ac.fillStyle = '#ddd';
      ac.fillRect(this.x, this.y, this.w, this.h);
      ac.font = '12px sans-serif';
      ac.fillStyle = '#000';
      ac.textBaseline = 'top';
      return ac.fillText('Draw here!', this.x, this.y);
    };

    return DrawingArea;

  })();
});
