// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['core/player'], function(Player) {
  var Drawer;
  return Drawer = (function(_super) {

    __extends(Drawer, _super);

    function Drawer() {
      return Drawer.__super__.constructor.apply(this, arguments);
    }

    Drawer.prototype.role = 'drawer';

    Drawer.prototype.timeLeft = 60;

    Drawer.prototype.drawing = [];

    return Drawer;

  })(Player);
});
