// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['core/player'], function(Player) {
  var Guesser;
  return Guesser = (function(_super) {

    __extends(Guesser, _super);

    function Guesser() {
      return Guesser.__super__.constructor.apply(this, arguments);
    }

    Guesser.prototype.role = 'guesser';

    return Guesser;

  })(Player);
});
