// Generated by CoffeeScript 1.4.0

define(function() {
  var PlayerCard;
  return PlayerCard = (function() {

    PlayerCard.W = 160;

    PlayerCard.H = 120;

    PlayerCard.MARGIN = 16;

    PlayerCard.prototype.w = 160;

    PlayerCard.prototype.h = 120;

    PlayerCard.prototype.margin = 16;

    PlayerCard.prototype.x = 0;

    PlayerCard.prototype.y = 0;

    PlayerCard.prototype.FONTSIZE = 14;

    PlayerCard.prototype.wordsGuessed = null;

    PlayerCard.prototype.name = null;

    function PlayerCard(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      if (!(this.game != null)) {
        throw 'game was not set!';
      }
      this.resize().draw();
    }

    PlayerCard.prototype.reorganize = function() {
      var i;
      i = this.game.playerCards.indexOf(this);
      this.x = this.margin + i * (this.w + this.margin);
      return this;
    };

    PlayerCard.prototype.resize = function() {
      this.y = this.game.drawingArea.y + this.game.drawingArea.h + this.margin + this.game.timer.h + this.margin;
      return this;
    };

    PlayerCard.prototype.setTextStyle = function() {
      var ac;
      ac = atom.context;
      ac.textBaseline = 'middle';
      ac.textAlign = 'center';
      ac.font = "bold " + this.FONTSIZE + "px sans-serif";
      ac.fillStyle = '#000';
      return this;
    };

    PlayerCard.prototype.clear = function() {
      var ac;
      ac = atom.context;
      ac.clearRect(this.x, this.y, this.w, this.h);
      return this;
    };

    PlayerCard.prototype.draw = function() {
      var ac;
      ac = atom.context;
      this.clear();
      ac.strokeStyle = '#000';
      ac.lineWidth = 1;
      ac.fillStyle = '#efeffe';
      ac.fillRect(this.x, this.y, this.w, this.h);
      ac.strokeRect(this.x + 1, this.y + 1, this.w - 2, this.h - 2);
      this.setTextStyle();
      ac.fillText(this.name, this.x + (this.w >> 1), this.y + (this.h >> 1));
      return this;
    };

    return PlayerCard;

  })();
});
