// Generated by CoffeeScript 1.4.0

define(function() {
  var Round;
  return Round = (function() {

    function Round(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      if (!(this.game != null)) {
        throw 'game was not set!';
      }
    }

    Round.prototype.chooseWordPile = function() {};

    return Round;

  })();
});
