// Generated by CoffeeScript 1.4.0

define(function() {
  var StatDisplay;
  return StatDisplay = (function() {

    StatDisplay.prototype.margin = 8;

    function StatDisplay(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
    }

    StatDisplay.prototype.draw = function() {};

    return StatDisplay;

  })();
});
