// Generated by CoffeeScript 1.4.0

define(function() {
  var Timer;
  return Timer = (function() {

    Timer.prototype.x = 0;

    Timer.prototype.y = 0;

    Timer.prototype.margin = 16;

    Timer.prototype.FONTSIZE = 16;

    Timer.prototype.FACTORMINUTES = 0.000016666;

    Timer.prototype.FACTORSECONDS = 0.001;

    function Timer(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      if (!(this.game != null)) {
        throw 'game was not set!';
      }
      this.resize().draw();
    }

    Timer.prototype.setTextStyle = function() {
      var ac;
      ac = atom.context;
      ac.textBaseline = 'middle';
      ac.textAlign = 'center';
      ac.font = this.FONTSIZE + 'px sans-serif';
      ac.fillStyle = '#000';
    };

    Timer.prototype.draw = function() {
      var ac, minutes, seconds, time;
      ac = atom.context;
      ac.clearRect(this.x, this.y, this.w, this.h);
      ac.fillStyle = '#FCFFD9';
      ac.fillRect(this.x, this.y, this.w, this.h);
      this.setTextStyle();
      time = this.game.timeLeft();
      minutes = (time * this.FACTORMINUTES) >> 0;
      seconds = (time * this.FACTORSECONDS) >> 0;
      ac.fillText("" + minutes + " min " + seconds + " seconds left", this.x + (this.w >> 1), this.y + (this.h >> 1));
      return this;
    };

    Timer.prototype.resize = function() {
      this.x = this.margin;
      this.y = this.game.drawingArea.y + this.game.drawingArea.h + this.margin;
      this.w = atom.width - this.margin * 2;
      this.h = this.FONTSIZE + this.margin;
      return this;
    };

    return Timer;

  })();
});
